# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/venus2/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.			
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/bn/acclaim/extract-files.sh

# All the blobs necessary for Nook Tablet
PRODUCT_COPY_FILES  += \
	vendor/bn/acclaim/proprietary/bins/battery_log.sh:/system/bin/battery_log.sh \
	vendor/bn/acclaim/proprietary/bins/d2c_test:/system/bin/d2c_test \
	vendor/bn/acclaim/proprietary/bins/hostap:/system/bin/hostap \
	vendor/bn/acclaim/proprietary/bins/idme:/system/bin/idme \
	vendor/bn/acclaim/proprietary/bins/klog.sh:/system/bin/klog.sh \
	vendor/bn/acclaim/proprietary/bins/pvrsrvinit:/system/bin/pvrsrvinit \
	vendor/bn/acclaim/proprietary/bins/rild:/system/bin/rild \
	vendor/bn/acclaim/proprietary/bins/v4l2_gfx_client:/system/bin/v4l2_gfx_client \
	vendor/bn/acclaim/proprietary/bins/vold:/system/bin/vold \
	vendor/bn/acclaim/proprietary/ducati/base_image_app_m3.xem3:/system/lib/ducati/base_image_app_m3.xem3 \
	vendor/bn/acclaim/proprietary/ducati/base_image_sys_m3.xem3:/system/lib/ducati/base_image_sys_m3.xem3 \
	vendor/bn/acclaim/proprietary/etc/asound.conf:/system/etc/asound.conf \
	vendor/bn/acclaim/proprietary/etc/event-log-tags:/system/etc/event-log-tags \
	vendor/bn/acclaim/proprietary/hw/alsa.omap4.so:/system/lib/hw/alsa.omap4.so \
	vendor/bn/acclaim/proprietary/hw/gralloc.default.so:/system/lib/hw/gralloc.default.so \
	vendor/bn/acclaim/proprietary/hw/lights.omap4.so:/system/lib/hw/lights.omap4.so \
	vendor/bn/acclaim/proprietary/hw/overlay.omap4.so:/system/lib/hw/overlay.omap4.so \
	vendor/bn/acclaim/proprietary/hw/sensors.omap4.so:/system/lib/hw/sensors.omap4.so \
	vendor/bn/acclaim/proprietary/libafdrm.so:/system/lib/libafdrm.so \
	vendor/bn/acclaim/proprietary/libasound.so:/system/lib/libasound.so \
	vendor/bn/acclaim/proprietary/libaudioeffect_jni.so:/system/lib/libaudioeffect_jni.so \
	vendor/bn/acclaim/proprietary/libaudiopolicy.so:/system/lib/libaudiopolicy.so \
	vendor/bn/acclaim/proprietary/libaudio.so:/system/lib/libaudio.so \
	vendor/bn/acclaim/proprietary/libdrm1.so:/system/lib/libdrm1.so \
	vendor/bn/acclaim/proprietary/libdrmplay.so:/system/lib/libdrmplay.so \
	vendor/bn/acclaim/proprietary/libdrm_plugin.so:/system/lib/libdrm_plugin.so \
	vendor/bn/acclaim/proprietary/libGLESv1_CM.so:/system/lib/libGLESv1_CM.so \
	vendor/bn/acclaim/proprietary/libGLESv2.so:/system/lib/libGLESv2.so \
	vendor/bn/acclaim/proprietary/libjnigraphics.so:/system/lib/libjnigraphics.so \
	vendor/bn/acclaim/proprietary/libjni_latinime.so:/system/lib/libjni_latinime.so \
	vendor/bn/acclaim/proprietary/libjni_pinyinime.so:/system/lib/libjni_pinyinime.so \
	vendor/bn/acclaim/proprietary/libmedia_jni.so:/system/lib/libmedia_jni.so \
	vendor/bn/acclaim/proprietary/libnativehelper.so:/system/lib/libnativehelper.so \
	vendor/bn/acclaim/proprietary/libnetutils.so:/system/lib/libnetutils.so \
	vendor/bn/acclaim/proprietary/libpdfhost.so:/system/lib/libpdfhost.so \
	vendor/bn/acclaim/proprietary/libplayready.so:/system/lib/libplayready.so \
	vendor/bn/acclaim/proprietary/libreference-ril.so:/system/lib/libreference-ril.so \
	vendor/bn/acclaim/proprietary/libril.so:/system/lib/libril.so \
	vendor/bn/acclaim/proprietary/libRS.so:/system/lib/libRS.so \
	vendor/bn/acclaim/proprietary/librtp_jni.so:/system/lib/librtp_jni.so \
	vendor/bn/acclaim/proprietary/libsmapi.so:/system/lib/libsmapi.so \
	vendor/bn/acclaim/proprietary/libSR_AudioIn.so:/system/lib/libSR_AudioIn.so \
	vendor/bn/acclaim/proprietary/libsrec_jni.so:/system/lib/libsrec_jni.so \
	vendor/bn/acclaim/proprietary/libssl.so:/system/lib/libssl.so \
	vendor/bn/acclaim/proprietary/libTIPVR2DBLT.so:/system/lib/libTIPVR2DBLT.so \
	vendor/bn/acclaim/proprietary/libttssynthproxy.so:/system/lib/libttssynthproxy.so \
	vendor/bn/acclaim/proprietary/libui.so:/system/lib/libui.so \
	vendor/bn/acclaim/proprietary/libvorbisidec.so:/system/lib/libvorbisidec.so \
	vendor/bn/acclaim/proprietary/libysshared.so:/system/lib/libysshared.so \
	vendor/bn/acclaim/proprietary/vendor/lib/gralloc.omap4.so:/system/vendor/lib/hw/gralloc.omap4.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libEGL_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libGLESv1_CM_ORG_CF3D.so:/system/vendor/lib/egl/libGLESv1_CM_ORG_CF3D.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libGLESv1_CM_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libGLESv2_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libglslcompiler.so:/system/vendor/lib/libglslcompiler.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libIMGegl.so:/system/vendor/lib/libIMGegl.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libpvr2d.so:/system/vendor/lib/libpvr2d.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:/system/vendor/lib/libpvrANDROID_WSEGL.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libPVRScopeServices.so:/system/vendor/lib/libPVRScopeServices.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libsrv_init.so:/system/vendor/lib/libsrv_init.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libsrv_um.so:/system/vendor/lib/libsrv_um.so \
	vendor/bn/acclaim/proprietary/vendor/lib/libusc.so:/system/vendor/lib/libusc.so 

